### ISSUE TITLE
[BUG] Bot only listens to reactions after it is done reacting itself

### ISSUE THREAD

**Issue by RobertRR11** [Compliance-Resource-Pack/Discord-Bot#12]
**Describe the bug**
When doing any texture command which has multiple results, the bot only listens to the emoji reactions after it is done reacting itself. You would need to react again if you already reacted before.

**To Reproduce**
1. Any texture command that has multiple results, for example `/texture 32 oak`
2. React any emoji before the bot is done reacting

**Expected behavior**
That the bot already listens to the reactions before it is done.

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/57044042/103439201-155b0480-4c3b-11eb-8873-2498e903910c.png)

**On which discord did it happen?**
 - all of them

**Comment by Pomi108** [comment]
This has been happening again for a while now. Not sure when exactly it started.

**Comment by Juknum** [comment]
won't be fixed as we are rewriting the bot in ts, this is not really important and would automatically fixed in the rewrite
