### ISSUE TITLE
[BUG] Bot not listening to authors reactions after replying to itself

### ISSUE THREAD

**Issue by RobertRR11** [Compliance-Resource-Pack/Discord-Bot#128]
As example I'll take the texture command and its reactions.

When using the texture command and for example the tile reaction, due to the bot replying with the tiled image to the texture command message, the bot is the "author" of the command and then also replies with the magnified tiled image to itself, even though the original message author didn't react to magnify.
![image](https://user-images.githubusercontent.com/57044042/127020202-d632e783-8142-472d-8aaa-8c154f6a7d6c.png)

If you ignore the bot's reaction using `if (user.bot) return` the bot doesn't magnify its own image, but also doesn't listen to the original message author, due to the bot still being the "author" of the texture command message.
![image](https://user-images.githubusercontent.com/57044042/127020388-80819029-4fe6-4323-854e-2076bd7eca48.png)

This issue also applies to the texture submission reactions.

**Comment by Juknum** [comment]
The `if (user.bot) return` is used to avoid self-reacting commands, you have to find a solution for that then :/

**Comment by RobertRR11** [comment]
what

**Comment by Domi04151309** [comment]
Just save the last user and then check to use that when the bot is replying to itself
