### ISSUE TITLE
[REQUEST] djs 13 ui

### ISSUE THREAD

**Issue by nick-1666** [Compliance-Resource-Pack/Discord-Bot#155]
By utilising button, context and menu interactions in djs v13, the bot can handle things when received instead of listening for reactions making bot ui better with a reliable, elegant and usable solution.

This could be done by using an interaction handler and a few files of js to replace the emoji ui. Since context commands have to be registered like slash commands, i suggest adding options for magnifying,tileing, palleting and guidelines as those are commonly used (but keep original commands to them aswell)

note: i have done this before to a previous bot that used emojis and it took a week but was well received by my - now inactive - server.

**Comment by RobertRR11** [comment]
Yes we have been planning this for some time now and are starting to slowly implement various features. But right now we can't do any slash commands due to some current limitations, for example no image support, which is needed for many of our commands.

**Comment by nick-1666** [comment]
Context menus and buttons can and should be used for a more understandable ui. Slash commands kinda suck imo i dont like how they prefill args

**Comment by nick-1666** [comment]
im workin on an implementation now on a fork

**Comment by RobertRR11** [comment]
> Context menus and buttons can and should be used for a more understandable ui. Slash commands kinda suck imo i dont like how they prefill args

I have already started to use buttons in some locations and wanted to expand it in the future. Also I wanted to do an own constructor function for them for various reasons.
https://github.com/Compliance-Resource-Pack/Discord-Bot/blob/master/events/messageCreate.js#L60
https://github.com/Compliance-Resource-Pack/Discord-Bot/blob/master/commands/Fun/kill.js#L52
