### ISSUE TITLE
[BUG] *Texture Commands Broken in DMs*

### ISSUE THREAD

**Issue by BellPepperBrian** [Compliance-Resource-Pack/Discord-Bot#163]
**Describe the bug**
When you use Complibot in DMs, a few commands such as /quote works; however, I cannot do /texture 16 (or 32) whenever I want to grab a texture.  For example /texture 32 dirt, won't work, nor does the /animate command.

**To Reproduce**
1. Go into CompliBot DMs.
2. Do either /texture 16 dirt, /texture 32 dirt, or /animate (on a texture that can be animated).
3. Bot doesn't respond.

**Expected behavior**
It's suppose to give me the dirt texture or any other texture that I requested.

**Screenshots**
![image](https://user-images.githubusercontent.com/74277198/147961439-bb30e331-fac6-4020-8a22-3e1f16fac13a.png)

**Comment by nick-1666** [comment]
This probably won't get fixed since slash commands are made on guilds instead of globally. I forgot why we did that but im sure it was for a good reason, ask Juknum since he implemented / commands

**Comment by RobertRR11** [comment]
Actually, I can't reproduce that issue and the /texture command works for me in DM's. May have also been fixed sometime by another change.
