### ISSUE TITLE
Rewrite bot in TypeScript

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/Discord-Bot#164]
- [x] Implements slashs commands
   - [x] Fix handler for guild only and global commands 
   >  slash commands are deployed per guilds, if the bot join a new guild, slash commands are fetched & bot restarted.
   - [x] Basic setup
   - [x] Add subcommands
   - [x] ~~Watch for implementing command group~~ (Not needed)
- [x] Extends class to add methods where it's needed
   - [x] Extends `EmbedMessage` to add a default color ('BLURPLE') 
   - [x] Extends `Message` with `warnUser(text: string)` (now renamed `warn`)
   - [x] Extends `Interactions` classes:
     - [x] `CommandInteraction` 
     - [x] `ButtonInteraction`
     - [x] `SelectMenuInteraction`

**Comment by nick-1666** [comment]
Slash commands proven to work. Good job Juk

**Comment by Juknum** [comment]
Updated slash commands todo

**Comment by nick-1666** [comment]
frick
