### ISSUE TITLE
[BUG] Timing issue with JSON database

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/Discord-Bot#31]
**Describe the bug**
Sometimes, JSON files are read and updated at the same time, causing desync issues.
Ex: mute command: if someone is muted while the bot actualizes the mute countdown, the newly muted user could be not muted or the countdown is not decreased.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to mute someone when the bot updated muted list.

**Expected behaviour**
A working database

**Additional context**
Do not change the countdown time process, if the bot updates the file less than each 30s, you can't write in the file anymore
Might be related to the autopush issue (contributors removed between 2 push)

**Comment by TheRolfFR** [comment]
What you need to do is use the same object to do all your operations.

Create a global object which is an handler object with a queue. Do one operation at a time. Create a Promise based system to do your operations. You could even create a local copy when possible. Why do you need to store mute users. When you can't you could create a [file lock system.](https://stackoverflow.com/a/51138921/6594899)
