### ISSUE TITLE
[BUG] Bot crash when using commands related to json read/write

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/Discord-Bot#38]
**Describe the bug**
The bot crash after doing `/contributor` or `/push`
The bot executes the command, then don't respond to any new commands & goes offline (crash).

**To Reproduce**
1. Get a computer
2. Get a keyboard
3. Get a discord account
4. Go anywhere where the bot is
5. Type /push <anything that's works>
6. Bot dies

**Expected behavior**
Do not crash?

**Screenshots**
Nothing showing up in the console

**Additional context**
Might be, and have to be related to #33

**Comment by RobertRR11** [comment]
fixed in #39
