### ISSUE TITLE
Create compare request

### ISSUE THREAD

**Issue by TheRolfFR** [Compliance-Resource-Pack/Discord-Bot#69]
**/compare** a command to compare a texture with the corresponding vanilla texture (with magnifying built-in)

**Comment by TheRolfFR** [comment]
@RobertRR11 Could you be more specific ?

**Comment by RobertRR11** [comment]
uh idk how to be more specific on that

for example you post a oak log texture and want to compare it with the current texture in the pack, so you would just type "/compare oak_log" and the bot would place the posted texture and the current texture from the pack side by side

**Comment by RobertRR11** [comment]
Was added in #77
