### ISSUE TITLE
[BUG] /contributor Author deletion only delete java xor bedrock

### ISSUE THREAD

**Issue by TheRolfFR** [Compliance-Resource-Pack/Discord-Bot#70]
**Describe the bug**
When adding is intelligent enough to know if it is a bedrock texture, remove only removes it on the selected edition.

**To Reproduce**
Add a texture contribution which is on java and bedrock
Remove the contribution of the previous result and push
See committed bedrock contribution

**Expected behavior**
Remove both

**Comment by RobertRR11** [comment]
Is this issue still up-to-date with the new database?

**Comment by Juknum** [comment]
No, but the /contributor command needs to be reworked.
