### ISSUE TITLE
[BUG] JSON are not updated after GetResults

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/Discord-Bot#76]
**Describe the bug**
When executing the GetResults function, everything seems to works, but when checking the local JSON, contributors are not updated and the JSON commit is empty (-> no file modified)

**To Reproduce**
1. run the function GetResults 
2. See that nothing changed inside JSON files

**Expected behavior**
Authors should be added

**Additional context**
Might be, (but idk honestly) related to the file handler system.

**Comment by Juknum** [comment]
UPDATE: only one contributor is added, that's mean that each time multiple contributor are added, the bot fetch the JSON repo, clearing previously added contributors

**Comment by RobertRR11** [comment]
Looks like the JSON's aren't updating at all anymore

**Comment by TheRolfFR** [comment]
Comment the pull part, i'll see what I can do

**Comment by Juknum** [comment]
This shouldn't be an issue anymore when the new database will be setup ;)

**Comment by Juknum** [comment]
Fixed since the new database is applied
