### ISSUE TITLE
[REQUEST] Changes to /instapass

### ISSUE THREAD

**Issue by Pomi108** [Compliance-Resource-Pack/Discord-Bot#79]
I think it would be better for the /instapass command to post its messages in #results rather than #submit-java or #submit-bedrock. This would make compiling changelogs a lot easier for me.  
Additionally, instead of the embed just displaying "the council has decided to instapass this texture", it should show the author, the texture, and the file name, just like the other messages in #results.

**Comment by Juknum** [comment]
Fixed with the new submission process
The `/instapass` command have been integrated into a reaction settings (react with it to instapass a texture)

Note: Requested changes have been applied, the texture is directly sent to #results and is added to GitHub with others during the autopush
