### ISSUE TITLE
[BUG] Magnify commands doesn't support transparency

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/Discord-Bot#89]
**Describe the bug**
Transparency goes brr when magnifying an image which has transparent pixels

**To Reproduce**
1. use /texture 32 tinted_glass
2. use the magnifying glass to automatically magnify it
3. see those transparent pixels become opaques.

**Expected behavior**
Pixels using alpha values should stay transparent after process.

**Screenshots**
![image](https://user-images.githubusercontent.com/49886317/117486618-2493eb00-af6a-11eb-942b-b4e356a1c032.png)

**Additional context**
Should be related to the output extension which is JPEG (JPEG doesn't support transparency) (I might be wrong)

**Comment by TheRolfFR** [comment]
Okay, so image data gives a with an integer between 0 and 255, so you just have to divide by 255 to get a float between 0 and 1 used in css rgba representation

https://github.com/Compliance-Resource-Pack/Discord-Bot/commit/9f942050a2a32d3c3a90920e5edd514c2856735b
